export type Deal = {
  id: string;
  kind: "flight" | "stay" | "car" | "package";
  from?: string;
  to: string;
  toCity: string;
  toCityFr: string;
  country: string;
  countryFr: string;
  image: string;
  imageAlt: string;
  imageAltFr: string;
  priceCad: number;
  wasCad?: number;
  badge?: string;
  badgeFr?: string;
  nights?: number;
  blurb: string;
  blurbFr: string;
};

export const DEALS: Deal[] = [
  {
    id: "lis-fall",
    kind: "flight",
    from: "YYC",
    to: "LIS",
    toCity: "Lisbon",
    toCityFr: "Lisbonne",
    country: "Portugal",
    countryFr: "Portugal",
    image: "https://images.unsplash.com/photo-1555881400-74d7acaacd8b?auto=format&fit=crop&w=1400&q=80",
    imageAlt: "Tram on a hillside street in Lisbon",
    imageAltFr: "Tramway dans une rue en pente à Lisbonne",
    priceCad: 589,
    wasCad: 869,
    badge: "32% off",
    badgeFr: "−32 %",
    blurb: "Round-trip from Calgary · shoulder-season fares",
    blurbFr: "Aller-retour au départ de Calgary · hors saison",
  },
  {
    id: "cun-sun",
    kind: "package",
    from: "YYZ",
    to: "CUN",
    toCity: "Cancún",
    toCityFr: "Cancún",
    country: "Mexico",
    countryFr: "Mexique",
    image: "https://images.unsplash.com/photo-1510097467424-192d713fd8b2?auto=format&fit=crop&w=1400&q=80",
    imageAlt: "Turquoise water and white sand in Cancún",
    imageAltFr: "Eau turquoise et sable blanc à Cancún",
    priceCad: 1249,
    wasCad: 1699,
    nights: 7,
    badge: "Flight + stay",
    badgeFr: "Vol + séjour",
    blurb: "7 nights from Toronto · all-in starting price",
    blurbFr: "7 nuits au départ de Toronto · prix de départ tout compris",
  },
  {
    id: "nrt-spring",
    kind: "flight",
    from: "YVR",
    to: "NRT",
    toCity: "Tokyo",
    toCityFr: "Tokyo",
    country: "Japan",
    countryFr: "Japon",
    image: "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?auto=format&fit=crop&w=1400&q=80",
    imageAlt: "Shibuya crossing in Tokyo at dusk",
    imageAltFr: "Carrefour de Shibuya à Tokyo au crépuscule",
    priceCad: 798,
    wasCad: 1149,
    badge: "Deal of the week",
    badgeFr: "Aubaine de la semaine",
    blurb: "Round-trip from Vancouver",
    blurbFr: "Aller-retour au départ de Vancouver",
  },
  {
    id: "cdg-stay",
    kind: "stay",
    to: "CDG",
    toCity: "Paris",
    toCityFr: "Paris",
    country: "France",
    countryFr: "France",
    image: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=1400&q=80",
    imageAlt: "Eiffel Tower above Paris rooftops",
    imageAltFr: "Tour Eiffel au-dessus des toits de Paris",
    priceCad: 189,
    nights: 1,
    badge: "From / night",
    badgeFr: "À partir de / nuit",
    blurb: "Central stays compared across partners",
    blurbFr: "Séjours au centre comparés chez nos partenaires",
  },
  {
    id: "lhr-weekend",
    kind: "flight",
    from: "YUL",
    to: "LHR",
    toCity: "London",
    toCityFr: "Londres",
    country: "United Kingdom",
    countryFr: "Royaume-Uni",
    image: "https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?auto=format&fit=crop&w=1400&q=80",
    imageAlt: "Tower Bridge in London",
    imageAltFr: "Tower Bridge à Londres",
    priceCad: 549,
    wasCad: 799,
    badge: "31% off",
    badgeFr: "−31 %",
    blurb: "Round-trip from Montréal",
    blurbFr: "Aller-retour au départ de Montréal",
  },
  {
    id: "fco-roma",
    kind: "package",
    from: "YYZ",
    to: "FCO",
    toCity: "Rome",
    toCityFr: "Rome",
    country: "Italy",
    countryFr: "Italie",
    image: "https://images.unsplash.com/photo-1552832230-c0197dd311b5?auto=format&fit=crop&w=1400&q=80",
    imageAlt: "Colosseum in Rome",
    imageAltFr: "Colisée à Rome",
    priceCad: 1549,
    wasCad: 1999,
    nights: 6,
    badge: "City break",
    badgeFr: "Escapade urbaine",
    blurb: "6 nights from Toronto · flight + hotel",
    blurbFr: "6 nuits au départ de Toronto · vol + hôtel",
  },
  {
    id: "kef-north",
    kind: "flight",
    from: "YHZ",
    to: "KEF",
    toCity: "Reykjavík",
    toCityFr: "Reykjavík",
    country: "Iceland",
    countryFr: "Islande",
    image: "https://images.unsplash.com/photo-1504829857797-ddff29c27927?auto=format&fit=crop&w=1400&q=80",
    imageAlt: "Icelandic waterfall and mossy cliffs",
    imageAltFr: "Cascade islandaise et falaises moussues",
    priceCad: 429,
    wasCad: 689,
    badge: "Atlantic hop",
    badgeFr: "Saut atlantique",
    blurb: "Round-trip from Halifax",
    blurbFr: "Aller-retour au départ de Halifax",
  },
  {
    id: "bcn-car",
    kind: "car",
    to: "BCN",
    toCity: "Barcelona",
    toCityFr: "Barcelone",
    country: "Spain",
    countryFr: "Espagne",
    image: "https://images.unsplash.com/photo-1539037116277-4db20889f2d4?auto=format&fit=crop&w=1400&q=80",
    imageAlt: "Colorful buildings along a Barcelona street",
    imageAltFr: "Immeubles colorés dans une rue de Barcelone",
    priceCad: 38,
    badge: "Per day",
    badgeFr: "Par jour",
    blurb: "Compact cars from downtown & airport",
    blurbFr: "Voitures compactes au centre-ville et à l'aéroport",
  },
];

export const DEST_PHOTOS: Record<string, string> = {
  LHR: "https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?auto=format&fit=crop&w=1400&q=80",
  CDG: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?auto=format&fit=crop&w=1400&q=80",
  NRT: "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?auto=format&fit=crop&w=1400&q=80",
  FCO: "https://images.unsplash.com/photo-1552832230-c0197dd311b5?auto=format&fit=crop&w=1400&q=80",
  CUN: "https://images.unsplash.com/photo-1510097467424-192d713fd8b2?auto=format&fit=crop&w=1400&q=80",
  JFK: "https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9?auto=format&fit=crop&w=1400&q=80",
  DUB: "https://images.unsplash.com/photo-1549918864-48ac978761a4?auto=format&fit=crop&w=1400&q=80",
  BCN: "https://images.unsplash.com/photo-1539037116277-4db20889f2d4?auto=format&fit=crop&w=1400&q=80",
  LIS: "https://images.unsplash.com/photo-1555881400-74d7acaacd8b?auto=format&fit=crop&w=1400&q=80",
  AMS: "https://images.unsplash.com/photo-1534351590666-13e3e96b5017?auto=format&fit=crop&w=1400&q=80",
  LAX: "https://images.unsplash.com/photo-1515895309288-a3815ab7cf81?auto=format&fit=crop&w=1400&q=80",
  MCO: "https://images.unsplash.com/photo-1530089711124-9ca31fb9e863?auto=format&fit=crop&w=1400&q=80",
  KEF: "https://images.unsplash.com/photo-1504829857797-ddff29c27927?auto=format&fit=crop&w=1400&q=80",
  ICN: "https://images.unsplash.com/photo-1534274988757-a28bf1a57c17?auto=format&fit=crop&w=1400&q=80",
  HNL: "https://images.unsplash.com/photo-1507876466758-bc54f384809c?auto=format&fit=crop&w=1400&q=80",
  MEX: "https://images.unsplash.com/photo-1518659526054-190340b32735?auto=format&fit=crop&w=1400&q=80",
};
